POST http://localhost:8080
Content-Type: application/json

{
  "name": 100.00,
  "balance": 500.00,
  "amount": 500.00,
  "iban": "NL61EVIL0332546753",
  "toIban": "NL61RABO0332543622",
  "processed": true
}