spring:
  application:
    name: payment-engine

  kafka:
    streams:
      properties:
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='<tenant>' password='token:<token>';
        sasl.mechanism: PLAIN
        basic.auth.credentials.source: USER_INFO
        basic.auth.user.info: <tenant>:token:<token>
        schema.registry.url: https://<cluster>.streaming.datastax.com:8081
        default:
          key.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
          value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
          deserialization.exception.handler: "org.apache.kafka.streams.errors.LogAndContinueExceptionHandler"
          production.exception.handler: "nl.adesso.streaming.exception.handler.CustomProductionExceptionHandler"
        specific.avro.reader: true
      security:
        protocol: SASL_SSL
      replication-factor: 1
    bootstrap-servers: <cluster>>.streaming.datastax.com:9093

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true

server:
  port: 52415